# Generated by Django 5.0.4 on 2026-09-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='commitChain',
            field=models.CharField(blank=True, default='regSoshCP31gSfl6p3mLw8dZ', max_length=50),
        ),
    ]
