# Generated by Django 5.0.4 on 2026-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='commitChain',
            field=models.CharField(blank=True, default='regSoshCP31gSfl6p3mLw8dZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='modlVer',
            field=models.IntegerField(default=2),
        ),
    ]
