# Generated by Django 5.0.4 on 2026-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='rewardsData',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
