# Generated by Django 5.0.4 on 2026-09-10 03:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='chain_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=250),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(blank=True, default='auto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='plugin_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=250),
        ),
        migrations.AlterField(
            model_name='node',
            name='region_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=250),
        ),
    ]
