# Generated by Django 5.0.4 on 2026-09-10 04:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_node_chain_array_alter_node_node_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='chain_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), blank=True, null=True, size=250),
        ),
        migrations.AlterField(
            model_name='node',
            name='plugin_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), blank=True, null=True, size=250),
        ),
        migrations.AlterField(
            model_name='node',
            name='region_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), blank=True, null=True, size=250),
        ),
    ]
