# Generated by Django 5.0.4 on 2026-09-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_node_chain_array_alter_node_plugin_array_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereview',
            name='creator_reveal_violations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodereview',
            name='reveal_success',
            field=models.FloatField(default=0.5),
        ),
    ]
