# Generated by Django 5.0.4 on 2026-08-02 14:53

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('networkChain', models.CharField(blank=True, default='User', max_length=50)),
                ('commitChain', models.CharField(blank=True, default='Accounts', max_length=50)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('modlVer', models.IntegerField(default=1)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('nodeCreatorId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('pattern', models.IntegerField(default=0)),
                ('signkey_dt', models.DateTimeField(blank=True, null=True)),
                ('alerts', models.JSONField(blank=True, default=dict, null=True)),
                ('signed', models.JSONField(default=dict)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('modlVer', models.IntegerField(default=1)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('networkChain', models.CharField(default='Region', max_length=25)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('func', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('validatorNodeId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('Chamber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('Link', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Content', models.TextField(blank=True, default=None, null=True)),
                ('targetUsers', models.JSONField(blank=True, default=dict, null=True)),
                ('pointerId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('validated', models.BooleanField(blank=True, default=False, null=True)),
                ('signed', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SuperSign',
            fields=[
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('signed', models.JSONField(default=dict)),
                ('networkChain', models.CharField(blank=True, default='Sonet', max_length=50)),
                ('modlVer', models.IntegerField(default=1)),
                ('pointerId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('networkChain', models.CharField(default='User', max_length=25)),
                ('modlVer', models.IntegerField(default=1)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('postId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('pointerId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('pointerHash', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('addonId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('addonHash', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('updateId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('updateHash', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('voteValue', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('saved', models.BooleanField(blank=True, default=None, null=True)),
                ('follow', models.BooleanField(blank=True, default=None, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('rmv', models.BooleanField(blank=True, default=None, null=True)),
                ('signed', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-lastUpdate'],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('modlVer', models.IntegerField(default=1)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('signed', models.JSONField(default=dict)),
                ('userId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('region_set_date', models.DateTimeField(blank=True, null=True)),
                ('localities', models.TextField(blank=True, default='[]', null=True)),
                ('interests', models.TextField(blank=True, default='[]', null=True)),
                ('follow_topics', models.TextField(blank=True, default='[]', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('modlVer', models.IntegerField(default=1)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
                ('new', models.BooleanField(default=True)),
                ('signed', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserPubKey',
            fields=[
                ('networkChain', models.CharField(default='Keys', max_length=25)),
                ('modlVer', models.IntegerField(default=1)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('end_life_dt', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('keyType', models.CharField(default='signing', max_length=25)),
                ('algorithm', models.CharField(default='secp256k1', max_length=25)),
                ('nodeId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('publicKey', utils.models.BinaryBase64urlField(2592, blank=True, editable=True, null=True)),
                ('signed', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('signed', models.JSONField(default=dict)),
                ('networkChain', models.CharField(blank=True, default='User', max_length=50)),
                ('modlVer', models.IntegerField(default=1)),
                ('validatorNodeId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('userId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('super_invalid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
    ]
