# Generated by Django 5.0.4 on 2026-08-02 14:53

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('networkChain', models.CharField(blank=True, default='User', max_length=50)),
                ('commitChain', models.CharField(blank=True, default='Plugin', max_length=50)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('modlVer', models.IntegerField(default=1)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('Name', models.CharField(blank=True, default='Main', max_length=50, null=True)),
                ('value', models.TextField(default='0')),
                ('signed', models.JSONField(default=dict)),
                ('Block_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block')),
                ('User_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('networkChain', models.CharField(blank=True, default='Wallet', max_length=50)),
                ('modlVer', models.IntegerField(default=1)),
                ('id', utils.models.BinaryBase62Field(30, default=None, editable=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added_to_node', models.DateTimeField(auto_now_add=True, null=True)),
                ('validations', models.JSONField(blank=True, default=dict, null=True)),
                ('senderChainGenId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('senderBlockId', utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True)),
                ('token_value', models.TextField(default='0')),
                ('regarding', models.JSONField(blank=True, default=None, null=True)),
                ('validated', models.BooleanField(blank=True, default=None, null=True)),
                ('enact_dt', models.DateTimeField(blank=True, null=True)),
                ('enacted', models.BooleanField(blank=True, default=None, null=True)),
                ('signed', models.JSONField(default=dict)),
                ('ReceiverBlock_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_block', to='network.block')),
                ('SenderBlock_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_block', to='network.block')),
                ('ReceiverWallet_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='transactions.wallet')),
                ('SenderWallet_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='transactions.wallet')),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
    ]
