# Generated by Django 5.0.4 on 2026-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token_value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
