# Generated by Django 5.0.4 on 2026-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_token_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token_value',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
