# Generated by Django 5.0.4 on 2026-08-18 21:40

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_token_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='senderChainGenId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiverNetworkChain',
            field=utils.models.BinaryBase62Field(30, blank=True, editable=True, null=True),
        ),
    ]
