from django.urls import path, re_path, include
from . import views as util_views

urlpatterns = [
    path('calendar_widget', util_views.calendar_widget_view),
    re_path('remove_notification/(?P<iden>[\w-]+)', util_views.remove_notification_view),
    re_path('continue_reading/(?P<iden>[\w-]+)', util_views.continue_reading_view),
    re_path('show_all/(?P<iden>[\w-]+)/(?P<item>[\w-]+)', util_views.show_all_view),
    
    #----utils
    path('is_sonet', util_views.is_sonet_view),
    path('get_sonet', util_views.get_sonet_view),
    path('set_object_data', util_views.set_object_data_view),
    re_path('get_object_data/(?P<obj_type>(.*))', util_views.get_object_data_view),
    path('get_object_data', util_views.get_object_data_view, {'obj_type':'Region'}),
    path('get_object_id', util_views.get_object_id_view),
    path('can_you_see_me', util_views.can_you_see_me_view),
    path('myip', util_views.myip_view),
    path('workers_status', util_views.workers_status_view),
    path('proxyme', util_views.proxyme_view),
    re_path('fetch_cloudflare_bundle/(?P<node_id>(.*))', util_views.fetch_cloudflare_bundle_view),

    re_path('mobile_share/(?P<iden>(.*))', util_views.mobile_share_view),
    re_path('modal_picker/(?P<modal_type>(.*))/(?P<iden>(.*))', util_views.modal_picker_view),
    re_path('default_modal/(?P<iden>(.*))', util_views.default_modal_view),
    re_path('share_modal/(?P<iden>(.*))', util_views.share_modal_view),
    re_path('post_insight_modal/(?P<iden>(.*))', util_views.post_insight_view),
    re_path('post_more_options_modal/(?P<iden>(.*))', util_views.post_more_options_view),
    re_path('verify_post_modal/(?P<iden>(.*))', util_views.verify_post_view),
    re_path('generic_modal_data/(?P<func>[\w-]+)/(?P<iden>(.*))', util_views.generic_modal_data_view),
    path('super', util_views.super_view),
    path('tester1', util_views.tester_queue_view),
    path('html_playground1', util_views.html_playground_view),
    path('daily_summarizer', util_views.daily_summarizer_view),
    path('run_notifications', util_views.add_test_notification_view),
    
    re_path('supersign/(?P<iden>(.*))', util_views.supersign_view, name='supersign'),
    re_path('supersign', util_views.supersign_view, {'iden':''}, name='supersign'),
    re_path('broadcast_datapackets', util_views.broadcast_datapackets_view),
    re_path('tidy_up', util_views.tidy_up_view),
    re_path('test_tasker', util_views.test_tasker_view),
    re_path('show_log/(?P<iden>(.*))', util_views.show_log_view),
    re_path('resume_processes', util_views.resume_processes_view),
    re_path('resume_process/(?P<iden>(.*))', util_views.resume_process_view),

    path('remove_false_blocks', util_views.remove_false_blocks_view),
    re_path('create_test_blocks', util_views.create_test_blocks_view),
    re_path('create_test_block/(?P<name>(.*))', util_views.create_test_block_view),
    re_path('check_validation_consensus/(?P<iden>(.*))', util_views.check_validation_consensus_view),
    re_path('make_not_valid/(?P<iden>(.*))', util_views.make_not_valid_view),
    re_path('make_valid_unknown/(?P<iden>(.*))', util_views.make_valid_unknown_view),
    re_path('invalidate_test_blocks', util_views.invalidate_test_blocks_view),
    re_path('get_assignment/(?P<iden>(.*))/', util_views.get_assignment_view),
    path('get_model_fields', util_views.get_model_fields_view),
    re_path('logs/(?P<logtype>(.*))/', util_views.node_logs_view),
    # path('node_logs', util_views.node_logs_view),
    # path('error_logs', util_views.error_logs_view),
    path('initial_setup', util_views.initial_setup_view),
    path('validate_test_data', util_views.validate_test_data_view),
    path('clear_test_data', util_views.clear_test_data_view),
    re_path('scrapers/(?P<region>(.*))/(?P<test>[\w-]+)', util_views.scrapers_view),
    re_path('run_super_function/(?P<region>(.*))/(?P<func>[\w-]+)/(?P<worker>[\w-]+)/(?P<super>[\w-]+)', util_views.run_super_function_view),
    re_path('run_super_function/(?P<region>(.*))/(?P<func>[\w-]+)', util_views.run_super_function_view, {'worker':'True','super':'False'}),
    re_path('remove_target_test_data_confirm/(?P<region>(.*))/(?P<model>[\w-]+)', util_views.remove_target_test_data_confirm_view),
    re_path('remove_target_test_data/(?P<region>(.*))/(?P<model>[\w-]+)', util_views.remove_target_test_data_view),

    path('django-rq/', include('django_rq.urls')),

]
