# Generated by Django 5.0.4 on 2026-08-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legis', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
    ]
