# Generated by Django 5.0.4 on 2026-08-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legis', '0002_initial'),
        ('network', '0002_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='action',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='action',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='action',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='bill',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='BillText_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_billtext_obj', to='legis.billtext'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='committee',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='district',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='district',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='district',
            name='ProvState_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_provstate_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='election',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='election',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='election',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='election',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.district'),
        ),
        migrations.AddField(
            model_name='election',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='election',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='government',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='government',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='government',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='government',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='government',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='election',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='action',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='legisuseraction',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.block'),
        ),
        migrations.AddField(
            model_name='legisuseraction',
            name='District_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='legisuseraction',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='legisuseraction',
            name='User_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Bill_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.bill'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='motion',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='party',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='party',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='party',
            name='ProvState_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_provstate_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.party'),
        ),
        migrations.AddField(
            model_name='person',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='person',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='person',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='person',
            name='ImageFile_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_imagefile_obj', to='posts.imagefile'),
        ),
        migrations.AddField(
            model_name='person',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='person',
            name='Update_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_obj', to='posts.update'),
        ),
        migrations.AddField(
            model_name='person',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.person'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Chair_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committee_chair', to='legis.person'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.person'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='statement',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='statement',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Meeting_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_key', to='legis.meeting'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.party'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.person'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
        migrations.AddField(
            model_name='userregisteredvote',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.block'),
        ),
        migrations.AddField(
            model_name='userregisteredvote',
            name='District_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='userregisteredvote',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='userregisteredvote',
            name='User_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_obj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userregisteredvote',
            name='Voter_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_voter_obj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.block'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='vote',
            name='CreatorNode_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.node'),
        ),
        migrations.AddField(
            model_name='vote',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Motion_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.motion'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.party'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legis.person'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.validator'),
        ),
    ]
