# Generated by Django 4.2.30 on 2026-08-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtext',
            name='networkChain',
        ),
        migrations.AddField(
            model_name='action',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='billtext',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='committee',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='motion',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AddField(
            model_name='vote',
            name='commitChain',
            field=models.CharField(blank=True, default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='committee',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='motion',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='statement',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
    ]
