# Generated by Django 5.0.4 on 2026-09-08 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0003_initial'),
        ('network', '0003_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegisUserAction',
            new_name='LegisPlay',
        ),
    ]
