# Generated by Django 4.2.30 on 2026-08-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0004_remove_billtext_networkchain_action_commitchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtext',
            name='networkChain',
            field=models.CharField(blank=True, default='Region', max_length=50),
        ),
    ]
