# Generated by Django 4.2.30 on 2026-08-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_initial'),
        ('posts', '0001_initial'),
        ('legis', '0005_billtext_networkchain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='RepVote',
        ),
        migrations.AlterField(
            model_name='district',
            name='modlVer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='government',
            name='modlVer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='modlVer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='modlVer',
            field=models.IntegerField(default=1),
        ),
    ]
