"""
Django settings for sovote project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

print('os.geteuid() == 0',os.geteuid() == 0)

sys.path.append(os.path.expanduser("~/Sonet/.data"))
import json

# from utils.models import prnt
try:

    file_path = os.path.expanduser("~") + f"/Sonet/.data/special/settings.py"
    with open(file_path, 'rb') as file:
        encrypted_data = file.read()
        settings_json = json.loads(encrypted_data)
except Exception as e:
    print('settings err 1',str(e))
    settings_json = {'CUSTOM_SECRET_KEY':'x','CUSTOM_DEBUG':True}

try:
    from special.trusted_sources import ADDRESSES
except ImportError as e:
    ADDRESSES = []

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http:\/\/[a-z2-7]{16,56}\.onion$", 
]
ALLOWED_HOSTS = ['127.0.0.1','.onion']
trusted_origins = []
if 'ADDRESS' in settings_json and settings_json['ADDRESS']:
    trusted_origins.append(f"https://{settings_json['ADDRESS']}")
    trusted_origins.append(f"http://{settings_json['ADDRESS']}")
    ALLOWED_HOSTS.append(settings_json['ADDRESS'])
if 'ONION' in settings_json and settings_json['ONION']:
    trusted_origins.append(f"https://{settings_json['ONION']}")
    trusted_origins.append(f"http://{settings_json['ONION']}")
    ALLOWED_HOSTS.append(settings_json['ONION'])
if 'DOMAIN' in settings_json and settings_json['DOMAIN']:
    trusted_origins.append(f"https://{settings_json['DOMAIN']}")
    trusted_origins.append(f"https://www.{settings_json['DOMAIN']}")
    ALLOWED_HOSTS.append(f".{settings_json['DOMAIN']}")
    ALLOWED_HOSTS.append(f"www.{settings_json['DOMAIN']}")
    cors_domain = settings_json['DOMAIN']
    import re
    CORS_ALLOWED_ORIGIN_REGEXES.append(rf"^https:\/\/(.+\.)?{re.escape(cors_domain)}$")
if 'PORT' in settings_json and settings_json['PORT']:
    trusted_origins.append(f"http://127.0.0.1:{settings_json['PORT']}")
    if 'EXTERNAL_IP' in settings_json and settings_json['EXTERNAL_IP']:
        trusted_origins.append(f"https://{settings_json['EXTERNAL_IP']}:{settings_json['PORT']}")
        trusted_origins.append(f"http://{settings_json['EXTERNAL_IP']}:{settings_json['PORT']}")
        ALLOWED_HOSTS.append(settings_json['EXTERNAL_IP'])
    if 'LOCAL_IP' in settings_json and settings_json['LOCAL_IP']:
        trusted_origins.append(f"http://{settings_json['LOCAL_IP']}:{settings_json['PORT']}")
        ALLOWED_HOSTS.append(settings_json['LOCAL_IP'])

if ADDRESSES:
    trusted_origins = trusted_origins + ADDRESSES

SECRET_KEY = settings_json['CUSTOM_SECRET_KEY']

DEBUG = settings_json['CUSTOM_DEBUG'] if isinstance(settings_json['CUSTOM_DEBUG'], bool) else settings_json['CUSTOM_DEBUG'] == 'True'

settings_json.clear()

CSRF_TRUSTED_ORIGINS = trusted_origins

# CORS_ALLOW_HEADERS = ['*']
# CORS_ALLOWED_ORIGINS = [i.lower() for i in trusted_origins]
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https:\/\/.*\.mydomain\.com$",
# ]
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https:\/\/([a-zA-Z0-9-]+\.)*mydomain\.com$",
# ]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'django_user_agents',
    "django_rq",
    'accounts',
    'network',
    'utils',
    'posts',
    'legis',
    'transactions',
    'geoip2',
    'django_crontab',
    "corsheaders",
    'django_social_share',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# If you use django-cors-headers, comment this out:
# INSTALLED_APPS.remove('corsheaders')
# MIDDLEWARE.remove('corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'sonet.urls'
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT, 'Templates'), PROJECT_ROOT],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sonet.wsgi.application'


SESSION_COOKIE_AGE = 15811200 # 6 months
SESSION_SAVE_EVERY_REQUEST = True


CRONJOBS = [
    ('*/10 * * * *', 'utils.cronjobs.task_runner'),
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'so_data',
        'USER': 'queue',
        'PASSWORD': 'K9V43S2P1',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


RQ_QUEUES = {
    'main': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 7200,  # 2 hour
    },
    'high': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 7200,
    },
    'low': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 7200,
    },
    'chat': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 7200,
    },
    'super': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 7200,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

GEOIP_PATH = os.path.join(PROJECT_ROOT,  'geoip')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static_cdn')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

